### ISSUE TITLE
[제안] swiftUI처럼 코드로 만들어진 레이아웃의 프리뷰를 확인 할 수 있는 방법 제공

### ISSUE THREAD

**Issue by gmlwhdtjd** [ioskrew/SwiftLayout#11]
- 앱을 실행하지 않더라도 동작할 수 있었으면 좋겠음
- swiftUI의 PreviewProvider를 활용하는 방안

**Comment by oozoofrog** [comment]
아 PreviewProvider가 있군요! 고맙습니다.

**Comment by oozoofrog** [comment]
<img width="1552" alt="스크린샷 2022-02-07 오전 12 55 49" src="https://user-images.githubusercontent.com/3011832/152689336-06afc62c-59aa-4f3f-9014-5049fcb0d14e.png">
