### ISSUE TITLE
2.1.0

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#155]
- [ ] ~support macOS since 10.15~
- [x] more flags for SwiftLayoutPrinter
- [x] suffix for SwiftLayout like `sl`? or something (this needs discussion) #156 
- [x] performance improvement
  ```swift
  class View: UIView, Layoutable {
    func someFunction() {
      self.sl.layout() // new
      self.updateLayout() // deprecation
    }
  }
  ```

@gmlwhdtjd do you have any progressing or expecting features?

**Comment by gmlwhdtjd** [comment]
If more flags are going to be added than now, it would be better to consider using `OptionSet`.

**Comment by oozoofrog** [comment]
> If more flags are going to be added than now, it would be better to consider using `OptionSet`.

very agree
