### ISSUE TITLE
prefix for Layoutable

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#156]
do we needs like this?

```swift
class View: UIView, Layoutable {
  func someFunction() {
    self.sl.layout() // new
    self.updateLayout() // deprecation
  }
}
```swift

**Comment by gmlwhdtjd** [comment]
I think it is right to include `sl` in `Layoutable`.
But should I also add a way like this for overall unity?
```swift
UIView().sl {
  UIView().sl.anchors {
    Anchors.allSides()
  }.sublayout {
    UILayout()
  }
}
```

**Comment by oozoofrog** [comment]
> 

I was think about that too. but, unlike **updateLayout**, i think **anchors** are not very common naming. and parameter of it is unique, it can be handling through overloading in my guess.
callAsFunction may be come us to be problems. but like case of **anchors**, rarely used and almost same usage in my guess.
I cannot think convenience way of usage more than this.
To put it a little harder, if naming overlaps, I’m sure our methods will provide better usability.

**Comment by oozoofrog** [comment]
> I think it is right to include `sl` in `Layoutable`. But should I also add a way like this for overall unity?
> 
> ```swift
> UIView().sl {
>   UIView().sl.anchors {
>     Anchors.allSides()
>   }.sublayout {
>     UILabel()
>   }
> }
> ```


I was think about that too. but, unlike **updateLayout**, i think **anchors** are not very common naming. and parameter of it is unique, it can be handling through overloading in my guess.
callAsFunction may be come us to be problems. but like case of **anchors**, rarely used and almost same usage in my guess.
I cannot think convenience way of usage more than this.
To put it a little harder, if naming overlaps, I’m sure our methods will provide better usability.

**Comment by gmlwhdtjd** [comment]
I think you're right
In the case of extensions to UIView,  are not very common naming and parameter of it is unique, so it won't be a problem.
I think it would be better to think about it again when there is a request from users in the future.
you don't need to be shaken with the conviction that we are providing a better way.

**Comment by oozoofrog** [comment]
> I think you're right
> In the case of extensions to UIView, are not very common naming and parameter of it is unique, so it won't be a problem.
> I think it would be better to think about it again when there is a request from users in the future.
> you don't need to be shaken with the conviction that we are providing a better way.

gooood
