### ISSUE TITLE
sample for DocC

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#157]
i need funny idea...
i try some business card things but not funny... can't possible not funny works. @gmlwhdtjd 
great jobs give me funny power.

**Comment by gmlwhdtjd** [comment]
Funny, easy, full of useful examples🤯

Um...
At first, I'd like to focus on what is highlight of packages.
- Easy way of using UIKit/AppKit
- Using conditional and loop statements
- and so on

So, the tutorial should include 
- how to draw slightly complex views using packages
- how to use flags or loops for layout
- how to use LayoutProperty
- how to use SwiftLayoutPrinter
- etc.

**Comment by oozoofrog** [comment]
> Funny, easy, full of useful examples🤯
> 
> Um... At first, I'd like to focus on what is highlight of packages.
> 
> * Easy way of using UIKit/AppKit
> * Using conditional and loop statements
> * and so on
> 
> So, the tutorial should include
> 
> * how to draw slightly complex views using packages
> * how to use flags or loops for layout
> * how to use `Layoutable` and `LayoutProperty`
> * how to use `SwiftLayoutPrinter`
> * etc.

ok we can remove useful thing hahahaha

**Comment by gmlwhdtjd** [comment]
@oozoofrog 
Currently we are providing SwiftLayout-Sample
So how about closing this issue?

**Comment by oozoofrog** [comment]
> @oozoofrog
> Currently we are providing SwiftLayout-Sample
> So how about closing this issue?

very agreed
