### ISSUE TITLE
support SwiftUI

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#200]
```swift
class SampleUIView: UIView, Layoutable {
  ...
}
struct SampleView: View {
  var body: some View {
    VStack {
      Text("HELLO")
      SampleUIView(frame: .zero).sl.swiftUI
  }
}
```

I forgot this 😹

- [x] support SwiftUI with sl.swiftUI
- [x] support print view information for debugging at updating ui view

**Comment by gmlwhdtjd** [comment]
It seems to be the same as issue #197 
I'll close issue it.
