### ISSUE TITLE
no member constant?

### ISSUE THREAD

**Issue by Gargo** [ioskrew/SwiftLayout#278]
From your readme:
```
Anchors.top.constant(10)
Anchors.top.multiplier(10)
```

My code:
```
view.sublayout {
            v.anchors {
                Anchors.top.constant(28)
            }
        }.finalActive()
```

The following error occurs during compilation:
`Value of type 'AnchorsExpression<AnchorsYAxisAttribute>' has no member 'constant'`

If I call it correctly when I need to set particular constraints for some views only (`addSubview` is already called before)

**Comment by kakao-jay-choi** [comment]
We replaced the description in the develop branch, but it's late to reflect the main branch. Please check the develop branch for the correct description before reflecting it. Thank you.

**Comment by kakao-jay-choi** [comment]
We replaced the description in the develop branch, but it's late to reflect the main branch. Please check the develop branch for the correct description before reflecting it. thank you .

**Comment by oozoofrog** [comment]
We replaced the description in the develop branch, but it's late to reflect the main branch. Please check the develop branch for the correct description before reflecting it. Thank you.
https://github.com/ioskrew/SwiftLayout/blob/develop/README.md
