### ISSUE TITLE
glue to SwiftUI

### ISSUE THREAD

**Issue by oozoofrog** [ioskrew/SwiftLayout#99]

**Comment by gmlwhdtjd** [comment]
Is it working LayoutBuilding+SwiftUI.swift?
There seems to be something wrong

**Comment by oozoofrog** [comment]
> Is it working LayoutBuilding+SwiftUI.swift?
> There seems to be something wrong

oh no. I check this. 🫣

**Comment by oozoofrog** [comment]
> Is it working LayoutBuilding+SwiftUI.swift?
> There seems to be something wrong

it's working :)
